import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QuizProvider from "./context/QuizContext";
import { AuthProvider } from "./context/AuthContext";

import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quiznest",
  description: "Generated by Ahmed Hassan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <QuizProvider>
            <div className="flex h-screen">
              <Sidebar />
              <div className="flex-1 flex flex-col overflow-hidden">
                <Navbar />
                <main className="flex-1 overflow-auto bg-gray-50 dark:bg-gray-900">
                  {children}
                </main>
              </div>
            </div>
          </QuizProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
